/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BaseContract__factory } from "./BaseContract__factory";
export { GalacticCollectibles__factory } from "./GalacticCollectibles__factory";
